-d D:\src\tn_vdp\fpga\tn_vdp_v1\impl\gwsynthesis\tn_vdp.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\src\tn_vdp\fpga\tn_vdp_v1\src\tn_vdp.cst
-cfg D:\src\tn_vdp\fpga\tn_vdp_v1\impl\pnr\device.cfg
-sdc D:\src\tn_vdp\fpga\tn_vdp_v1\src\tn_vdp.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 1
-route_option 1
-correct_hold 1
-route_maxfan 23
